package com.kedacom.extractor.convertor;

import com.kedacom.extractor.response.CaseInfo;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import request.CaseInformation;

import java.util.List;

@Mapper(componentModel = "spring")
public interface ResultConvertor {
//    @Mapping(target = "uploadUser", source = "cjyh")
//    @Mapping(target = "uploadTime", source = "cjsj")
//    @Mapping(target = "uploadRole", source = "cjr")
//    @Mapping(target = "updateUser", source = "zxgxyh")
//    @Mapping(target = "updateTime", source = "zxgxsj")
//    @Mapping(target = "updateRole", source = "zxgxr")
//    @Mapping(target = "targetSelection", source = "xzdx")
//    @Mapping(target = "solveUnitName", source = "solve_unit_name")
//    @Mapping(target = "solveUnit", source = "padw")
//    @Mapping(target = "solveCaseTime", source = "pasj")
//    @Mapping(target = "siteSelection", source = "xzcs")
//    @Mapping(target = "reportedUnit", source = "jjdw")
//    @Mapping(target = "reportedPeople", source = "jjry")
//    @Mapping(target = "recordCaseTime", source = "lasj")
//    @Mapping(target = "perpetratorCount", source = "zhzacy")
//    @Mapping(target = "origNo", source = "jqbh")
////    @Mapping(target = "lossSituation", source = "sazjz")
//    @Mapping(target = "longitude", source = "map_x")
//    @Mapping(target = "latitude", source = "map_y")
//    @Mapping(target = "isSerial", source = "is_serial")
//    @Mapping(target = "isScene", source = "is_scene")
//    @Mapping(target = "isInvestigation", source = "sfxcky")
//    @Mapping(target = "injuryPart", source = "injury_part")
//    @Mapping(target = "harmLevel", source = "ajwhcd")
//    @Mapping(target = "endTime", source = "afsj_js")
//    @Mapping(target = "crimeTime", source = "xzsj_jh")
//    @Mapping(target = "crimeSceneInvestigateNo", source = "xckyh")
//    @Mapping(target = "crimeLocale", source = "afddxxdz")
//    @Mapping(target = "crimeFeature", source = "crime_feature")
//    @Mapping(target = "createUser", source = "lryh")
//    @Mapping(target = "createDepart", source = "lrdw")
//    @Mapping(target = "classifyStatus", source = "classify_status")
//    @Mapping(target = "caseTags", source = "case_tags")
//    @Mapping(target = "caseStatus", source = "ajzt")
//    @Mapping(target = "caseSource", source = "ajly")
//    @Mapping(target = "caseNo", source = "ajbh")
//    @Mapping(target = "caseNature", source = "ajxz")
//    @Mapping(target = "caseName", source = "ajmc")
//    @Mapping(target = "caseIdentify", source = "aj_id")
//    @Mapping(target = "caseDescription", source = "jyaq")
//    @Mapping(target = "caseCategory", source = "ajlx")
//    @Mapping(target = "caseAttributes", source = "case_attributes")
//    @Mapping(target = "cantonName", source = "afddxzqhmc")
//    @Mapping(target = "beginTime", source = "afsj_ks")
//    @Mapping(target = "alarmWay", source = "bafs")
//    @Mapping(target = "alarmUnit", source = "bjrgzdw")
//    @Mapping(target = "alarmTime", source = "jjsj")
//    @Mapping(target = "alarmReasons", source = "jqlb")
//    @Mapping(target = "alarmPeopleState", source = "bjms")
//    @Mapping(target = "alarmPeople", source = "barxm")
//    @Mapping(target = "alarmCall", source = "bardh")
//    @Mapping(target = "adminRegionValue", source = "gsdwmc")
//    @Mapping(target = "adminRegionCd", source = "gsdw")
//    @Mapping(target = "acceptUnit", source = "ajsldw")
//    @Mapping(target = "acceptTime", source = "slsj")
//    @Mapping(target = "acceptPeople", source = "ajslr")
    public List<CaseInformation> caseResultToRequest(List<CaseInfo> caseInfos);

    @Mapping(target = "uploadUser", source = "cjyh")
    @Mapping(target = "uploadTime", source = "cjsj")
    @Mapping(target = "uploadRole", source = "cjr")
    @Mapping(target = "updateUser", source = "zxgxyh")
    @Mapping(target = "updateTime", source = "zxgxsj")
    @Mapping(target = "updateRole", source = "zxgxr")
    @Mapping(target = "targetSelection", source = "xzdx")
    @Mapping(target = "solveUnitName", source = "solve_unit_name")
    @Mapping(target = "solveUnit", source = "padw")
    @Mapping(target = "solveCaseTime", source = "pasj")
    @Mapping(target = "siteSelection", source = "xzcs")
    @Mapping(target = "reportedUnit", source = "jjdw")
    @Mapping(target = "reportedPeople", source = "jjry")
    @Mapping(target = "recordCaseTime", source = "lasj")
    @Mapping(target = "perpetratorCount", source = "zhzacy")
    @Mapping(target = "origNo", source = "jqbh")
    @Mapping(target = "lossSituation", source = "sazjz")
    @Mapping(target = "longitude", source = "map_x")
    @Mapping(target = "latitude", source = "map_y")
    @Mapping(target = "isSerial", source = "is_serial")
    @Mapping(target = "isScene", source = "is_scene")
    @Mapping(target = "isInvestigation", source = "sfxcky")
    @Mapping(target = "injuryPart", source = "injury_part")
    @Mapping(target = "harmLevel", source = "ajwhcd")
    @Mapping(target = "endTime", source = "afsj_js")
    @Mapping(target = "crimeTime", source = "xzsj_jh")
    @Mapping(target = "crimeSceneInvestigateNo", source = "xckyh")
    @Mapping(target = "crimeLocale", source = "afddxxdz")
    @Mapping(target = "crimeFeature", source = "crime_feature")
    @Mapping(target = "createUser", source = "lryh")
    @Mapping(target = "createDepart", source = "lrdw")
    @Mapping(target = "classifyStatus", source = "classify_status")
    @Mapping(target = "caseTags", source = "case_tags")
    @Mapping(target = "caseStatus", source = "ajzt")
    @Mapping(target = "caseSource", source = "ajly")
    @Mapping(target = "caseNo", source = "ajbh")
    @Mapping(target = "caseNature", source = "ajxz")
    @Mapping(target = "caseName", source = "ajmc")
    @Mapping(target = "caseIdentify", source = "aj_id")
    @Mapping(target = "caseDescription", source = "jyaq")
    @Mapping(target = "caseCategory", source = "ajlx")
    @Mapping(target = "caseAttributes", source = "case_attributes")
    @Mapping(target = "cantonName", source = "afddxzqhmc")
    @Mapping(target = "cantonCode", source = "")
    @Mapping(target = "beginTime", source = "afsj_ks")
    @Mapping(target = "alarmWay", source = "bafs")
    @Mapping(target = "alarmUnit", source = "bjrgzdw")
    @Mapping(target = "alarmTime", source = "jjsj")
    @Mapping(target = "alarmReasons", source = "jqlb")
    @Mapping(target = "alarmPeopleState", source = "bjms")
    @Mapping(target = "alarmPeople", source = "barxm")
    @Mapping(target = "alarmCall", source = "bardh")
    @Mapping(target = "adminRegionValue", source = "gsdwmc")
    @Mapping(target = "adminRegionCd", source = "gsdw")
    @Mapping(target = "acceptUnit", source = "ajsldw")
    @Mapping(target = "acceptTime", source = "slsj")
    @Mapping(target = "acceptPeople", source = "ajslr")
    public CaseInformation caseResultToRequest(CaseInfo caseInfo);


}
